### ISSUE TITLE
Clarification of installation/development steps (jekyll --watch vs jekyll --livereload)

### ISSUE THREAD

**Issue by posiczko** [ElMassimo/jekyll-vite#6]
Hello  Máximo!

Thank you for your work bringing Vite to the ruby/rails/jekyll worlds. I have a question regarding how to integrate vite in the jekyll context for the purpose of live/hot reloading.

The issue I have boils down to the following:

As far as I can tell, `jekyll serve` with a standard `--watch` flag is not watching changes that Vite is producing and is not propagating the changes to the browser. The same changes to the CSS are reloaded in the browser when `jekyll --livereload` is used.

For reference, I use [the following sample Jekyll blog](https://github.com/posiczko/jekyll-vite-blog) which was derived using [these steps](https://tetrapyloctomy.org/articles/2021/08/04/jekyll-vite.html). Standard entry points were used with addition of SASS pipeline.

Following your installation & [development](https://jekyll-vite.netlify.app/posts/development/) steps for Jekyll, I tried to run `bin/vite dev` while running `jekyll serve` with negative results, i.e. changes to `_frontend/minima/*scss` were not reflected in the browser. The were compiled by Vite from Jekyll, just not served. I got rid of `bin/vite` as jekyll seems to be running vite on its own.

Any hints on the proper setup?

**Comment by ElMassimo** [comment]
Hi Pawel! @posiczko

It's nice that you've done a write up on using jekyll-vite with minima, I had [answered a similar question earlier](https://github.com/ElMassimo/jekyll-vite/issues/4#issuecomment-889882282) but the name of the issue doesn't help for visibility.

I'll check the repo you provided and see what's happening with the setup. From what you've described, it's likely that Jekyll is not detecting the running Vite dev server.

In the meantime, try starting Vite first, and the Jekyll process later once Vite has started listening on its port, and see if that causes HMR to work as expected.

**Comment by posiczko** [comment]
Thank you for speedy reply! Interestingly, enforcing order during startup seems to fix the issue. Both `livereload` and `watch` seem to work!

**Comment by ElMassimo** [comment]
Nice to hear that!

I'll reopen in the meantime as a reminder to document the Procfile approach.

**Comment by ElMassimo** [comment]
Closed in https://github.com/ElMassimo/jekyll-vite/commit/b8adfbb94bc664cc825b08de6d5dac7d7e9e5bd9 and https://github.com/ElMassimo/jekyll-vite/commit/b76fd3f7468f9fae8c4adbbe41bd405bb73472b1.

Also, created [`jekyll-vite-minima`](https://github.com/ElMassimo/jekyll-vite-minima) with step-by-step instructions to setup Vite Ruby with the default theme (minima).

@posiczko Linked to your blog post in case folks want to use Vite to process the base stylesheets. Thanks for sharing! 😃
